inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'uploads/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Lint/SuppressedException:
  Enabled: false
